%YAML 1.2
---

# host infos
host_string: ''
host_port: '9090'
host_user: 'root'
host_pass: 'redhat'

# manually configured selenium hub
selenium_hub: ''

# avocado config
avocado_results_dir: ''

# versions of pkg/sys under test
test_pkg_ver: 'cockpit-ovirt-dashboard-0.14.13-2'
test_sys_ver: 'rhvh-4.4.3.1-0.20201105.0'
